# Generated by Django 5.0.14 on 2025-05-26 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='accounts.userprofile', verbose_name='Профиль пользователя'),
        ),
    ]
